spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_manager?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    # redis配置
  redis:
    host: localhost
    port: 6379
    database: 3